[package]
name = "g60"
version = "0.1.1"
authors = ["Julio Treviño <julio.tpaez@gmail.com>"]
description = "encodes and decodes G60 as bytes or utf8"
repository = "https://github.com/juliotpaez/rust-g60"
documentation = "https://docs.rs/g60"
readme = "README.md"
keywords = ["g60", "utf8", "encode", "decode"]
categories = ["encoding"]
license = "MIT"
edition = "2018"

[features]
random = ["rand"]
incorrect = []

[[bench]]
name = "benchmarks"
harness = false

[dependencies.rand]
version = "0.8.4"
optional = true
features = ["small_rng"]

[dev-dependencies]
criterion = "0.3.5"
rand = "0.8.4"